### PR TITLE
[Experimental] ERC-6105 No Intermediary NFT Trading Protocol

### LINKED ISSUE #149: [Experimental] ERC-6105 No Intermediary NFT Trading Protocol
Create and work inside folder `experimental/erc_6105_no_intermediary_nft_trading_protocol`:

This ERC adds a marketplace functionality to [ERC-721](https://eips.ethereum.org/EIPS/eip-721) to enable non-fungible token trading without relying on an intermediary trading platform. At the same time, creators may implement more diverse royalty schemes.

**Implementation Details:**
- The design and approach are left to the discretion of the assignee.
- Most current NFT trading relies on an NFT trading platform acting as an intermediary, which has lots of problems.

**Reference:** https://eips.ethereum.org/EIPS/eip-6105

+ TODO later:  Optional item offer extension and Optional collection offer extension

### PR DESCRIPTION
**Pull request by SoarinSkySagar**
closes #149 

**Changes:**
 - Added the implementation for `ERC-6105` in Cairo with fully documented codebase.
 - Added the implementation of `CollectionOffer` and `ItemOffer` extensions.
 - Wrote the tests for the contract, including the extensions and ensured that all tests pass.
 - Linted all Cairo code with `scarb fmt`.

### CODE REVIEW

**Comment by 0xandee** [comment]
@SoarinSkySagar Can you also write test files to demonstrate how it would work? tysm

**Comment by SoarinSkySagar** [comment]
> @SoarinSkySagar Can you also write test files to demonstrate how it would work? tysm

@0xandee can do, but the specifications for this erc doesn't contain any test cases for now hence I didn't write any. Still want me to write the tests?

**Comment by 0xandee** [comment]
> > @SoarinSkySagar Can you also write test files to demonstrate how it would work? tysm
> 
> @0xandee can do, but the specifications for this erc doesn't contain any test cases for now hence I didn't write any. Still want me to write the tests?

Yeah that would be great!

**Comment by 0xandee** [comment]
LGTM! Let's goooo!!!

**Pull request merged**
