### PR TITLE
test: Write unit tests for FlexDrop

### PR DESCRIPTION
**Pull request by LazarusAA**
Writing unit tests for FlexDrop, solves issue #81

### CODE REVIEW

**Comment by LazarusAA** [comment]
Hi @0xandee, I'm getting an error on line 190, it seems like the function `create_new_phase_drop()` is not being recognized despite the dispatcher, I've tried a few alternatives but can't quite get it working. Id really appreciate it if you could check it out.

image

**Comment by 0xandee** [comment]
> Hi @0xandee, I'm getting an error on line 190, it seems like the function `create_new_phase_drop()` is not being recognized despite the dispatcher, I've tried a few alternatives but can't quite get it working. Id really appreciate it if you could check it out.
> 
> image

Hey it's actually `start_new_phase_drop` function entry not found, can you double check on IFlexDropDispatcher aka FlexDrop contract address assignment?

**Comment by LazarusAA** [comment]
Okay I see, so `create_new_phase_drop` also calls `start_new_phase_drop`. But how could I call the `create_new_phase_drop()` function with both dispatchers?

**Comment by 0xandee** [comment]
Hey do you have any estimation on this issue @LazarusAA

**Pull request closed without merging**
