### PR TITLE
Experimental/fractional

### PR DESCRIPTION
**Pull request by casweeney**
### Fractional NFT Implementation
- Created a mock NFT (`ERC721`) contract named `FlexNFT` using Openzeppelin Component.
- Created a `FractionalNFT` contract that use `ERC20` tokens create fractions of an NFT.
- Added `Readme.md` to explain the implementation concept.
- Test has not been implemented yet, waiting for approval to continue, just to be sure this implementation looks like what's needed.

### CODE REVIEW

**Comment by casweeney** [comment]
@0xandee please I want if this implementation looks like what you want, and to know if I can proceed with the test.

**Comment by 0xandee** [comment]
> @0xandee please I want to know if this implementation looks like what you want, and to know if I can proceed with the test.

hey can you add some quick description inside a md file so I can fully understand it? Thanks!!

**Comment by casweeney** [comment]
> > @0xandee please I want to know if this implementation looks like what you want, and to know if I can proceed with the test.
> 
> hey can you add some quick description inside a md file so I can fully understand it? Thanks!!

Alright.

**Comment by casweeney** [comment]
Hi @0xandee, I have added a Readme file where I explained the implementation concept in the smart contracts.

**Pull request merged**
