### PR TITLE
Refactor deployment script for cleaner code

### LINKED ISSUE #78: dev: Refactor deployment script for cleaner code
Refactor `deployment.ts` in `marketplace/script/` folder. The current deployment script contains repetitive code. This issue aims to refactor the script to improve readability, reduce redundancy, and follow best practices for code organization.

`Additional Notes:` Please run a full test of the deployment process after refactoring to ensure that no functionality is broken.

### PR DESCRIPTION
**Pull request by RuneRogue**
The deployment of contracts with or without constructors is handled in one function, deployContract.
A separate function, initializeContract, is responsible for initializing contracts.
Repetitive tasks like adding currency or updating selectors are managed by handleContractAction, which simplifies adding new actions.
The contractsToDeploy array allows easy addition or modification of contracts in the deployment sequence.

Fixed #78

### CODE REVIEW

**Comment by 0xandee** [comment]
what is this bro @RuneRogue

**Comment by RuneRogue** [comment]
It's updated deployment script

**Comment by RuneRogue** [comment]
@0xandee  why did you closed it?

**Comment by 0xandee** [comment]
I didnt assign you this no?

**Comment by RuneRogue** [comment]
@0xandee but do I deserve a chance right? I have completed it first that's why I have raised a PR.

**Comment by 0xandee** [comment]
I think this PR was done first: https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/94 . But I'll merge yours too

**Pull request merged**
