### PR TITLE
Add a README for each experimental ERC [2]

### LINKED ISSUE #147: Add a README for each experimental ERC [2]
Add a README that includes the corresponding ERCs and the syntax changes for Starknet's Cairo. The README can replicate the content of the corresponding EIPs.

1. [erc_5643_subscription_nft](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/tree/main/experimental/erc_5643_subscription_nft)
2. [erc_6806_holding_time_tracking](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/tree/main/experimental/erc_6806_holding_time_tracking)

### PR DESCRIPTION
**Pull request by Benjtalkshow**
Closes #147 
Add README for ERC 6806 Holding Time Tracking

## Description of Changes
This pull request adds a README file for the ERC 6806 Holding Time Tracking implementation. The README includes:
- Overview of the ERC 6806 standard
- Project setup requirements
- Compilation and testing instructions
- License information

### CODE REVIEW

**Comment by 0xandee** [comment]
Add a README that includes the corresponding ERCs and the syntax changes for Starknet's Cairo. And you're missing [erc_5643_subscription_nft](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/tree/main/experimental/erc_5643_subscription_nft)

**Comment by Benjtalkshow** [comment]
> Add a README that includes the corresponding ERCs and the syntax changes for Starknet's Cairo. And you're missing [erc_5643_subscription_nft](https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/tree/main/experimental/erc_5643_subscription_nft)

Alright

**Comment by Benjtalkshow** [comment]
@0xandee 
I have modified my PR sir.

**Comment by 0xandee** [comment]
LGTM!

**Pull request merged**
