### PR TITLE
fix: update readme

### LINKED ISSUE #140: Fix README (without using chatgpt)
Improve and clean up the README file, without using chatgpt. Simple as that!

### PR DESCRIPTION
**Pull request by JosueBrenes**
closes #140 

### PR Description 📄✨

- 🚀 Simplified and reorganized the README for better readability and contributor experience.
- 🔧 Added detailed **Development Setup** section, including Scarb and Starknet Foundry installation.
- 📜 Enhanced structure with a clear **Repository Overview** and **Key Features**.
- 🖼️ Included visual guides for **Marketplace Actions** to improve user understanding.
- ✅ Highlighted essential commands for cloning, building, and testing contracts.

### CODE REVIEW

**Comment by 0xandee** [comment]
Can you also put contracts features from old README to corresponding README contract folder? @JosueBrenes

**Comment by JosueBrenes** [comment]
@0xandee ready for review

**Comment by JosueBrenes** [comment]
Is this how you wanted it?

**Comment by 0xandee** [comment]
Please don't delete everything! Just move the contracts features from the old README into the respective README in the contracts folder?

**Comment by JosueBrenes** [comment]
@0xandee ready

**Pull request closed without merging**
