### PR TITLE
test: write unit tests for erc721_open_edition

### LINKED ISSUE #80: test: Write unit tests for ERC721_open_edition and ERC721_open_edition_multi_metadata
Complete the unit test of `openedition/ERC721_open_edition.cairo` and `openedition/ERC721_open_edition_multi_metadata.cairo`, write test cases in `openedition/tests` folder.

Use `scarb test` to run all the tests.

All test cases are required to `PASS`.

### PR DESCRIPTION
**Pull request by zintarh**
Resolves #80

### CODE REVIEW

**Comment by kateberryd** [comment]
@0xandee I've written tests for `update_allowed_flex_drop` and `mint_flex_drop` functions in `ERC721_open_edition.cairo` but I can't write tests for `create_new_phase_drop` `update_phase_drop`, `update_creator_payout`, `update_payer` and `multi_configure` because they depend on `CurrencyManager` contract in the `marketplace` folder.

**Comment by 0xandee** [comment]
@kateberryd do you have any idea to resolve it?

**Comment by kateberryd** [comment]
@0xandee There are two possible ways to approach this

- Use a mock contract
- Make the root folder a scarb project so we can use `marketplace` and `openedition`  as packages

**Comment by 0xandee** [comment]
> @0xandee There are two possible ways to approach this
> 
> * Use a mock contract
> * Make the root folder a scarb project so we can use `marketplace` and `openedition`  as packages

hi have you able to resolve it?

**Comment by 0xandee** [comment]
Hey do you have any estimation on this issue @kateberryd

**Comment by kateberryd** [comment]
Hey @0xandee I'd finish it today. I apologize for the delay

**Pull request closed without merging**
